os: Visual Studio 2015

before_build:
  - nuget restore src\Renci.SshNet.VS2015.sln

build:
  project: src\Renci.SshNet.VS2015.sln
  verbosity: minimal

test:
  assemblies: src\Renci.SshNet.Tests\bin\Debug\Renci.SshNet.Tests.dll
  categories:
    except:
    - integration
    - LongRunning