os: Visual Studio 2015

before_build:
  - nuget restore src\Renci.SshNet.VS2015.sln

build:
  project: src\Renci.SshNet.VS2015.sln
  verbosity: minimal

on_success:
- cmd: vstest.console /logger:Appveyor src\Renci.SshNet.Tests\bin\Debug\Renci.SshNet.Tests.dll /TestCaseFilter:"TestCategory!=integration&TestCategory!=LongRunning"
- cmd: vstest.console /logger:Appveyor src\Renci.SshNet.Tests.NET35\bin\Debug\Renci.SshNet.Tests.NET35.dll /TestCaseFilter:"TestCategory!=integration&TestCategory!=LongRunning"